image: node:18

stages:
  - test
  - build
  - deploy

before_script:
  - apt-get update -y
  - apt-get install -y openssh-client

hello_ci:
  stage: test
  script:
    - echo "CI is working"
    - node -v
    - npm -v

build_backend:
  stage: build
  script:
    - echo "Building backend..."
    - npm install
    - echo "Backend build completed"
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  only:
    - main

deploy_backend:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying backend..."

    # ---------- SSH SETUP ----------
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H 64.227.180.201 >> ~/.ssh/known_hosts

    # ---------- DEPLOY COMMANDS ----------
    - ssh dhanjay-laptop@64.227.180.201 "
        cd /home/cinemasync_backend/cinemasync_backend &&
        git pull origin main &&
        npm install --production &&
        pm2 reload cinemasync || pm2 start src/index.js --name cinemasync
      "
